CREATE TABLE Users (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Places (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Adress VARCHAR(100) NOT NULL
);
